version: '3'
services:
    app:
        image: registry.cn-hangzhou.aliyuncs.com/kennylee/registry
        container_name: 'docker-registry'
        ports:
            - 5000:5000
        volumes:
            - /home/data/registry:/var/lib/registry
        restart: unless-stopped

