app:
    image: index.alauda.cn/kenny/docker-registry-v2-1-1
    container_name: 'registry'
    ports:
        - 5000:5000
    volumes:
        - /opt/data/registry2:/var/lib/registry
    restart: always
    environment:
        - REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY=/var/lib/registry
        - TZ=Asia/Shanghai
