version: '3'
services:
    docker_auth:
        image: cesanta/docker_auth
        container_name: 'docker_auth'
        ports:
            - "5001:5001"
        volumes:
            - ./data/docker_auth/auth_server/config:/config:ro
            - ./data/log/docker_auth:/logs
            - ./data/docker_auth/auth_server/ssl:/ssl
        command: /config/auth_config.yml
        restart: on-failure
        logging:
            driver: 'json-file'
            options:
                max-size: '30m'
                max-file: '1'
    registry:
        image: registry.cn-hangzhou.aliyuncs.com/kennylee/registry
        container_name: 'docker_registry'
        ports:
            - 5000:5000
        volumes:
            - ./data/docker_auth/auth_server/ssl:/ssl
            - ./data/registry2:/var/lib/registry
        restart: on-failure
        environment:
            - REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY=/var/lib/registry
            - REGISTRY_AUTH=token
            - REGISTRY_AUTH_TOKEN_REALM=https://192.168.1.100:5001/auth
            - REGISTRY_AUTH_TOKEN_SERVICE="Docker registry"
            - REGISTRY_AUTH_TOKEN_ISSUER="Auth Service"
            - REGISTRY_AUTH_TOKEN_ROOTCERTBUNDLE=/ssl/server.pem
            - REGISTRY_HTTP_TLS_CERTIFICATE=/ssl/server.pem
            - REGISTRY_HTTP_TLS_KEY=/ssl/server.key
        logging:
            driver: 'json-file'
            options:
                max-size: '30m'
                max-file: '1'

