version: '3'
services:
    app:
        image: registry.cn-hangzhou.aliyuncs.com/kennylee/registry
        container_name: 'docker-registry'
        ports:
            - 5000:5000
        volumes:
            - ./data/registry:/var/lib/registry
        restart: on-failure
        logging:
            driver: 'json-file'
            options:
                max-size: '30m'
                max-file: '1'

