version: '2'
services:
    app: 
        image: registry.cn-hangzhou.aliyuncs.com/kennylee/java:openjdk-8-jre
        volumes: 
            - ./app/app.jar:/data/app.jar
            - ./config/application.yml:/data/application.yml:ro
        ports: 
            - "8080:8080"
        entrypoint: 
            - java 
            - -jar 
            - /data/app.jar
            - --spring.config.location=/data/application.yml
