version: '2'
services:
    app:
        build: .
        ports:
            - "8080:8080"
        volumes:
            - ./data/webapps/:/opt/tomcat/webapps/:z
        environment:
            - TZ=Asia/Shanghai
        restart: always

