version: '2'
services:
    prometheus:
        image: registry.cn-hangzhou.aliyuncs.com/kennylee/prometheus:2.28.0
        container_name: prometheus
        restart: on-failure
        volumes:
            - ./data:/opt/bitnami/prometheus/data:z
        logging:
            driver: 'json-file'
            options:
                max-size: '10m'
                max-file: '1'
