version: '2'
services:
    web:
        build: nginx
        container_name: "gitbook-web"
        ports:
            - "3022:80"
        volumes: 
            - ./data/html/:/usr/share/nginx/html
        environment:
            - TZ=Asia/Shanghai
        restart: always
    ftp:
        build: ftp
        container_name: "gitbook-ftp"
        ports:
            - "3021:21"
            - "30000-30009:30000-30009"
        volumes:
            - ./data/html/:/usr/share/nginx/html
            - ./data/pure-ftpd:/etc/pure-ftpd
        restart: always
        privileged: true
        environment:
            - TZ=Asia/Shanghai
