version: '2.4'
services:
    web:
        image: registry.cn-hangzhou.aliyuncs.com/kennylee/nginx:alpine-1.13
        container_name: "nginx"
        ports:
            - "80:80"
        volumes:
            - ./data/html/:/usr/share/nginx/html
            - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf
            - ./nginx/conf/conf.d/:/etc/nginx/conf.d/
        restart: on-failure
        logging:
            driver: 'json-file'
            options:
                max-size: '12m'
                max-file: '5'
    ftp:
        build: ./ftp
        container_name: "ftpd_server"
        ports:
            - "21:21"
            - "30000-30009:30000-30009"
        volumes:
            - ./data/html/:/usr/share/nginx/html
            - ./data/pure-ftpd:/etc/pure-ftpd
        restart: on-failure
        privileged: true
        environment:
            - TZ=Asia/Shanghai
        logging:
            driver: 'json-file'
            options:
                max-size: '12m'
                max-file: '5'
