version: '2'

networks:
    &network net:
        driver: bridge
        ipam:
            driver: default
                
services:
    app:
        image: ${GITLAB_IMAGE}
        container_name: gitlab
        hostname: ${GITLAB_HOSTNAME}
        ports:
            - "${GITLAB_HTTP_PORT}:80"
            - "${GITLAB_SSH_PORT}:22"
        restart: always
        networks:
            - *network
        volumes:
            - ${GITLAB_DATA_PATH}:/var/opt/gitlab:z
            - ${GITLAB_LOGS_PATH}:/var/log/gitlab:z
            - ${GITLAB_CONFIG_PATH}:/etc/gitlab:z
        environment:
            GITLAB_OMNIBUS_CONFIG: |
                external_url "http://${GITLAB_HOSTNAME}:${GITLAB_HTTP_PORT}"
                gitlab_rails['gitlab_shell_ssh_port'] = ${GITLAB_SSH_PORT}
        logging:
            driver: 'json-file'
            options:
                max-size: '30m'
                max-file: '2'

