version: '2'

services:
    ftpd:
        image: registry.cn-hangzhou.aliyuncs.com/kennylee/pure-ftpd:stretch-latest
        container_name: "ftpd_server"
        ports:
            - "30000-30059:30000-30059"
            - "21:21"
        volumes:
            - ./data/files/:/home/ftpusers/
            - ./data/pure-ftpd/passwd:/etc/pure-ftpd/passwd
        environment:
            PUBLICHOST: ${PUBLICHOST}
            FTP_USER_NAME: ${FTP_USER_NAME}
            FTP_USER_PASS: ${FTP_USER_PASS}
            FTP_USER_HOME: /home/ftpusers/${FTP_USER_NAME}
            FTP_MAX_CLIENTS: 30
            FTP_MAX_CONNECTIONS: 10
            ADDED_FLAGS: "-p 30000:30059 -9 utf8"
        restart: on-failure
        logging:
            driver: 'json-file'
            options:
                max-size: '12m'
                max-file: '5'

