version: '2'
services:
    app:
        image: registry.cn-hangzhou.aliyuncs.com/kennylee/nexus3:3.9.0-01
        ports: 
            - 8081:8081
        container_name: nexus3
        restart: on-failure
        environment:
            - TZ=Asia/Shanghai
        volumes:
            - ./data/:/nexus-data/:z
