version: '2'
    
networks:
    &network http:
        driver: bridge

services:
    http:
        image: kennylee26/tnginx:2.2.0
        container_name: "nginx"
        ports:
            - "80:80"
        volumes:
            - ./config/nginx.conf:/etc/nginx/nginx.conf
            - ./config/conf.d/:/etc/nginx/conf.d/
        networks:
            - *network 
