version: '3'
    
services:
    app:
        image: registry.cn-hangzhou.aliyuncs.com/kennylee/mysql
        #build: ./
        ports: 
            - 3306:3306
        container_name: mysql
        restart: always
        environment:
            - MYSQL_ROOT_PASSWORD=111111
        volumes:
            - ./data/standalong:/var/lib/mysql/:z
            #- ./data/standalong-logs:/var/log/mysql/:z
        logging:
            driver: 'json-file'
            options:
                max-size: '30m'
                max-file: '1'

