server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://k8s.foo.com:30191/loki/api/v1/push

scrape_configs:
  - job_name: test-nginx-logs
    static_configs:
      - labels:
          job: 'test-nginx-logs'
          __path__: /tmp/logs/*.log
  - job_name: test-app-logs
    static_configs:
      - labels:
          job: 'test-app-logs'
          __path__: /tmp/logs/app-*/*.log
    pipeline_stages:
      - match:
          selector: '{job="test-app-logs"}'
          stages:
            - regex:
                source: filename
                expression: '(?:logs)/(?P<pod_name>\S+?)/'
            - labels:
                pod_name:
      - match: # for k8s Deployment Pods
          selector: '{job="test-app-logs"}'
          stages:
            - regex:
                source: pod_name
                expression: '^(?P<pod_collection>.+)-[^-]+$'
            - labels:
                pod_collection:
      - match: # for SpringBoot log
          selector: '{job="test-app-logs"}'
          stages:
            - regex:
                expression: '^(?P<year_month>\S+?)-(?P<days>[\d]{1,2})\s+(?P<time>[0-9:.]+?)\s+(?P<level>[A-Z]+?)\s+'
            - labels:
                level: