server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://192.168.1.96:30191/loki/api/v1/push

scrape_configs:
  - job_name: promtail-test-logs
    static_configs:
      - labels:
          app: 'test-logs'
          __path__: /tmp/logs/*.log

