version: '2'
services:
  #Service for nameserver
  namesrv:
    image: registry.cn-hangzhou.aliyuncs.com/kennylee/rocketmq:4.6-alpine
    container_name: rmqnamesrv
    ports:
      - 9876:9876
    volumes:
      - ./data/namesrv/logs:/home/rocketmq/logs
    command: sh mqnamesrv

  #Service for broker
  broker:
    image: registry.cn-hangzhou.aliyuncs.com/kennylee/rocketmq:4.6-alpine
    container_name: rmqbroker
    links:
      - namesrv
    ports:
      - 10909:10909
      - 10911:10911
      - 10912:10912
    environment:
      - NAMESRV_ADDR=namesrv:9876
    volumes:
      - ./data/broker/logs:/home/rocketmq/logs
      - ./data/broker/store:/home/rocketmq/store
    command: sh mqbroker

