version: '2'
services:
    app:
        image: gitlab/gitlab-ce:latest    
        container_name: gitlab
        ports:
            - "10080:80"
            - "10022:22"
        restart: always
        volumes:
            - ./data/gitlab/data:/var/opt/gitlab:z
            - ./data/gitlab/logs:/var/log/gitlab:z
            - ./data/gitlab/config:/etc/gitlab:z
        environment:
            - TZ=Asia/Shanghai
        networks:
            - new
#    runner:
        image: gitlab/gitlab-runner:latest
        container_name: gitlab-runner
        restart: always
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - ./data/gitlab-runner/config:/etc/gitlab-runner:Z
        environment:
            - TZ=Asia/Shanghai
        networks:
            new:
                aliases:
                    - gitlab-runner
networks:
  new:
