version: '2'
    
networks:
    &network wlsnet:
        driver: bridge

services:
    &admin adminserver:
        build: &image .
        container_name: wlsadmin
        ports:
            - "8001:8001"
        volumes:
            - './app/:/u01/oracle/app/'
        networks:
            - *network 
        env_file:
            - admin.env
    nm1:
        build: *image
        command: createServer.sh
        ports:
            - "7001:7001"
        volumes:
            - './app/:/u01/oracle/app/'
        networks:
            - *network 
        env_file:
            - app.env
        depends_on:
            - *admin
